#!/usr/bin/env php
<?php
$args = $argv;
$cmd = array_shift( $args );

chdir( dirname( __FILE__ ) );

$type = $args[0];

function report_status( $data ) {
	global $slug;

	$data['slug'] = $slug;
	echo json_encode( $data ) . "\n";
}

if ( ! isset( $args[1] ) || ! $args[1] ) {
	report_status( array(
		'type'    => 'error',
		'details' => 'Invalid slug.',
	) );
	die();
}

$slug = $args[1];

switch ( $type ) {
	case 'plugins':
		$download_path = sprintf(
			'zips/%s.zip',
			$slug
		);
		$download_url = sprintf(
			'https://downloads.wordpress.org/plugin/%s.latest-stable.zip?nostats=1',
			$slug
		);
		break;

	case 'themes':
		$download_path = sprintf(
			'zips/%s.zip',
			$slug
		);
		$download_url = sprintf(
			'https://downloads.wordpress.org/theme/%s.latest-stable.zip?nostats=1',
			$slug
		);
		break;

	default:
		report_status( array(
			'type'    => 'error',
			'details' => 'Invalid command.',
		) );
		die();
}

report_status( array(
	'type'          => 'start',
	'download_path' => $download_path,
	'download_url'  => $download_url,
) );

exec(
	'wget -q -np '
	. escapeshellarg( $download_url )
	. ' -O ' . escapeshellarg( $download_path )
	. ' > /dev/null',
	$output,
	$return
);

if ( $return === 0 && file_exists( $download_path ) ) {
	// The download succeeded.

	// Unzip the zip file, limiting to one zip at a time across all
	// processes.  Otherwise, for slow disk speeds, this tool spends most
	// of its time unzipping.  (For fast disks like SSDs this doesn't seem
	// to make much difference.)
	$unzip_lock = fopen( $type . '/.unzip_lock', 'w' );
	if ( ! $unzip_lock ) {
		report_status( array(
			'type'    => 'error',
			'details' => 'Failed to open unzip lockfile.',
		) );
		die();
	}

	if ( ! flock( $unzip_lock, LOCK_EX ) ) {
		report_status( array(
			'type'    => 'error',
			'details' => 'Failed to lock unzip lockfile.',
		) );
		die();
	}

	$initial = $slug[0];
	$filename = "{$type}/{$initial}/{$slug}";

	if ( file_exists( $filename ) ) {
		exec(
			sprintf(
				'rm -rf %s',
				escapeshellarg( $filename )
			)
		);
	}

	exec(
		sprintf(
			'unzip -o -d %s/%s %s',
			escapeshellarg( $type ),
			escapeshellarg( $initial ),
			escapeshellarg( $download_path )
		)
	);

	exec(
		sprintf(
			'rm -rf %s',
			escapeshellarg( $download_path )
		)
	);

	flock( $unzip_lock, LOCK_UN );
	fclose( $unzip_lock );

	report_status( array(
		'type' => 'done',
	) );

} else if ( $return === 8 ) {
	// Server issued an error response (404 for missing files).  See:
	// https://www.gnu.org/software/wget/manual/html_node/Exit-Status.html
	// TODO Detect 5xx errors

	report_status( array(
		'type'    => 'fail',
		'details' => 'Could not download zip.',
	) );

} else {
	// Some other error occurred.

	$error_message = "Bad exit code from `wget` ($return).";
	if ( $return === 127 ) {
		$error_message .= '  Make sure `wget` is installed.';
	}
	report_status( array(
		'type'    => 'error',
		'details' => $error_message,
	) );

}
